name: Build Perfil Parlamentar

on:
  pull_request:
  push:
    branches:
      - master
      - deploy-validacao

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Instala dependÃªncias
        working-directory: ./client
        run: npm install
      - name: Executa lint
        working-directory: ./client
        run: npm run lint
      - name: Executa build
        working-directory: ./client
        run: npm run build